import { UserProvider } from "./context/userContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="pt-br">
        <head>
          <meta charSet="utf-8"/> 
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <title>ORMAQ</title>
          
          
          {/*FONT*/}
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"/>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com"/>
          <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"/>

          {/*ICONS*/}
          <link rel="icon" type="image/x-icon" href="/image/logo-ormaq-amarela.png"></link>
          <link href="/css/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"/>

          {/*CSS*/}
          <link rel="stylesheet" href="/css/layout.css"/>
          <link rel="stylesheet" href="/css/listar.css"/>
          <link rel="stylesheet" href="/css/cadastrar.css"/>
          <link rel="stylesheet" href="/css/info.css"/>
          <link rel="stylesheet" href="/css/finalizar.css"/>
          <link rel="stylesheet" href="/css/login.css"/>
          <link rel="stylesheet" href="/css/classificados.css"/>
          <link rel="stylesheet" href="/css/exibirEquipamento.css"/>
        </head>

        <body className={``}>
          {children}  
        </body>
      </html>
    </UserProvider>
  );
}
